### ISSUE TITLE
[Checkbox] Theme flashes the secondary color after click

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web-catalog#277]
## Bug report
When the theme of a checkbox has been changed, clicking on the checkbox flashes the secondary color at the start and end of the aniamtion.

### Steps to reproduce
1. Go to https://material-components.github.io/material-components-web-catalog/#/component/theme
2. Click on The check boxes

### Actual behavior
The secondary color flashes 

### Expected behavior
The primary color should flash, not the secondary color

### Screenshots
![bug](https://user-images.githubusercontent.com/26075792/66823061-ec9d0f80-efa1-11e9-99be-5a73c0c27249.gif)

**Comment by Yavanosta** [comment]
Actually theme demo already removed, but problem was in the [way of styling components](https://github.com/material-components/material-components-web-catalog/blob/ef3ba95dda5a7c987886dcda1e5286c89dc92ccd/src/styles/ThemeCatalog.scss#L1) in demo:
```css
.theme-demo {
  $mdc-theme-primary: #fcb8ab;
  $mdc-theme-secondary: #feeae6;

  @import "@material/checkbox/mdc-checkbox";
}
```

```html
<div class="theme-demo">
  <div className='mdc-checkbox'>...</div>
</div>
```

In this case because of [this condition](https://github.com/material-components/material-components-web/blob/master/packages/mdc-checkbox/_mixins.scss#L306) wrong class for checkbox animation was generated `.theme-demo.mdc-checkbox--anim-unchecked-checked ....` (without space after `.theme-demo`).

Two components `mdc-top-app-bar` and `mdc-checkbox` are affected by this problem.

Including whole components style inside parent selector is considered as a bad practice, so no fixes on components side required. Since this code already removed from `material-components-web-catalog` no additional actions required.

Closing this issue.
